<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_1.map" md5sum="892c058c08544c38efc21b6b19031244" version="7.0.101" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.101
*
*   Mapping file:		XSLTransformation1_req_1.map
*   Map declaration(s):	XSLTransformation1_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FCustomerDomain-v1_0%252Fcom%252Fjunglesea%252Fbusinessservices%252Finterfaces%252FMaintainCustomerInformation%257DcreateCustomerRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FGreenLibrary%252Fcom%252Fjunglesea%252Fapps%252Fgreen%252FCustomerProfile%257DcreateCustomerAccountRequestMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="http://CustomerDomain-v1_0/com/junglesea/bo"
    xmlns:in3="http://CustomerDomain-v1_0/com/junglesea/businessservices/interfaces/MaintainCustomerInformation"
    xmlns:in4="http://CommonDomain-v1_0/com/junglesea/bo"
    xmlns:in2="wsdl.http://CustomerDomain-v1_0/com/junglesea/businessservices/interfaces/MaintainCustomerInformation"
    xmlns:in5="http://CustomerDomain-Msg/com/junglesea/bo"
    xmlns:out="http://GreenLibrary/com/junglesea/apps/green/CustomerProfile"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="http://GreenLibrary/com/junglesea/apps/green"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out3="wsdl.http://GreenLibrary/com/junglesea/apps/green/CustomerProfile"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://TestBed/xslt/XSLTransformation1_req_1"
    exclude-result-prefixes="in in3 in4 in2 in5 map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:XSLTransformation1_req_1"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:XSLTransformation1_req_1">
    <body>
      <out:createCustomerAccount>
        <input1>
          <!-- a simple data mapping: "in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/Name/FirstName"(string) to "firstName"(string) -->
          <xsl:if test="in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/Name/FirstName">
            <firstName>
              <xsl:value-of select="in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/Name/FirstName"/>
            </firstName>
          </xsl:if>
          <!-- a simple data mapping: "in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/Name/LastName"(string) to "lastName"(string) -->
          <xsl:if test="in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/Name/LastName">
            <lastName>
              <xsl:value-of select="in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/Name/LastName"/>
            </lastName>
          </xsl:if>
          <!-- a simple data mapping: "in3:createCustomer/inputParam/Customer/Party/Id"(string) to "type"(string) -->
          <xsl:if test="in3:createCustomer/inputParam/Customer/Party/Id">
            <type>
              <xsl:value-of select="in3:createCustomer/inputParam/Customer/Party/Id"/>
            </type>
          </xsl:if>
          <homeAddress>
            <!-- a simple data mapping: "in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/HomeAddress/LineOne"(string) to "line1"(string) -->
            <xsl:if test="in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/HomeAddress/LineOne">
              <line1>
                <xsl:value-of select="in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/HomeAddress/LineOne"/>
              </line1>
            </xsl:if>
            <!-- a simple data mapping: "in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/HomeAddress/LineTwo"(string) to "line2"(string) -->
            <xsl:if test="in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/HomeAddress/LineTwo">
              <line2>
                <xsl:value-of select="in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/HomeAddress/LineTwo"/>
              </line2>
            </xsl:if>
            <!-- a simple data mapping: "in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/HomeAddress/City"(string) to "city"(string) -->
            <xsl:if test="in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/HomeAddress/City">
              <city>
                <xsl:value-of select="in3:createCustomer/inputParam/Customer/Party/PartyDetails/Person/HomeAddress/City"/>
              </city>
            </xsl:if>
          </homeAddress>
        </input1>
      </out:createCustomerAccount>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
