<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_res_1.map" md5sum="af052ac71f3ea243f72824fee610a7fa" version="7.0.101" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.101
*
*   Mapping file:		XSLTransformation1_res_1.map
*   Map declaration(s):	XSLTransformation1_res_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FGreenLibrary%252Fcom%252Fjunglesea%252Fapps%252Fgreen%252FCustomerProfile%257DcreateCustomerAccountResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FCustomerDomain-v1_0%252Fcom%252Fjunglesea%252Fbusinessservices%252Finterfaces%252FMaintainCustomerInformation%257DcreateCustomerResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="http://GreenLibrary/com/junglesea/apps/green/CustomerProfile"
    xmlns:in2="http://GreenLibrary/com/junglesea/apps/green"
    xmlns:in3="wsdl.http://GreenLibrary/com/junglesea/apps/green/CustomerProfile"
    xmlns:out="http://CustomerDomain-v1_0/com/junglesea/bo"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out3="http://CustomerDomain-v1_0/com/junglesea/businessservices/interfaces/MaintainCustomerInformation"
    xmlns:out4="http://CommonDomain-v1_0/com/junglesea/bo"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:out2="wsdl.http://CustomerDomain-v1_0/com/junglesea/businessservices/interfaces/MaintainCustomerInformation"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:out5="http://CustomerDomain-Msg/com/junglesea/bo"
    xmlns:map="http://TestBed/xslt/XSLTransformation1_res_1"
    exclude-result-prefixes="in in2 in3 map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:XSLTransformation1_res_1"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:XSLTransformation1_res_1">
    <body>
      <out3:createCustomerResponse>
        <outputParam>
          <Customer>
            <!-- a simple mapping with no associated source:  to "CustomerId"(string) -->
            <CustomerId>
              <xsl:text>123456</xsl:text>
            </CustomerId>
          </Customer>
        </outputParam>
      </out3:createCustomerResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
