Create DB Orderdb;
CONNECT TO ORDERDB;
CREATE TABLE ADMINISTRATOR.SUPPLIERORDER ( ID VARCHAR (20)  NOT NULL , ORDERDATE DATE  NOT NULL , SHIPPERNAME VARCHAR (20) , SHIPPERSTREET VARCHAR (20) , SHIPPERCITY VARCHAR (10) , SHIPPERSTATE VARCHAR (10) , SHIPPERZIPCODE INTEGER , BILLERNAME VARCHAR (10) , BILLERSTREET VARCHAR (10) , BILLERCITY VARCHAR (10) , BILLERSTATE VARCHAR (10) , BILLERZIPCODE INTEGER , PRODUCTNAME VARCHAR (10) , PARTNUM VARCHAR (10) , QUANTITY INTEGER , USPRICE DECIMAL (2, 0) , SHIPDATE DATE , "COMMENT" VARCHAR (10)  ) ;
CONNECT RESET;
