<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="customGreetingExport1_customGreetingHttp_Service" targetNamespace="http://GreetingLibrary/com/junglesea/solution/greeting/interfaces/customGreeting/Binding3" xmlns:Port_0="http://GreetingLibrary/com/junglesea/solution/greeting/interfaces/customGreeting" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://GreetingLibrary/com/junglesea/solution/greeting/interfaces/customGreeting/Binding3" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="customGreeting.wsdl" namespace="http://GreetingLibrary/com/junglesea/solution/greeting/interfaces/customGreeting"/>
  <wsdl:binding name="customGreetingExport1_customGreetingHttpBinding" type="Port_0:customGreeting">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getGreeting">
      <soap:operation soapAction=""/>
      <wsdl:input name="getGreetingRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getGreetingResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="customGreetingExport1_customGreetingHttpService">
    <wsdl:port binding="this:customGreetingExport1_customGreetingHttpBinding" name="customGreetingExport1_customGreetingHttpPort">
      <soap:address location="http://localhost:9080/HelloMediatioModuleWeb/sca/customGreetingExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>