<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="MaintainInventoryInformation" targetNamespace="http://BizServices-InventoryMgmt/com/junglsea/businessservices/MaintainInventoryInformationArtifacts" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://BizServices-InventoryMgmt/com/junglsea/businessservices/MaintainInventoryInformationArtifacts" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl0="http://ProductDomain-v1_0/com/junglesea/businessservices/interfaces/MaintainInventoryInformation" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <plnk:partnerLinkType name="MaintainInventoryInformationPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:MaintainInventoryInformation"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <wsdl:import location="../../junglesea/businessservices/interfaces/MaintainInventoryInformation.wsdl" namespace="http://ProductDomain-v1_0/com/junglesea/businessservices/interfaces/MaintainInventoryInformation"/>
</wsdl:definitions>