<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="ProcessSPOrders" targetNamespace="http://BizServices-SupplierPartnerMgmt/com/junglsea/businessservices/ProcessSPOrdersArtifacts" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://BizServices-SupplierPartnerMgmt/com/junglsea/businessservices/ProcessSPOrdersArtifacts" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl0="http://SupplierPartnerDomain-v1_0/com/junglesea/businessservices/interfaces/ProcessSPOrders" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <plnk:partnerLinkType name="ProcessSPOrdersPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:ProcessSPOrders"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="ProcessSPOrdersPLT1">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:ProcessSPOrders"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="../../junglesea/businessservices/interfaces/ProcessSPOrders.wsdl" namespace="http://SupplierPartnerDomain-v1_0/com/junglesea/businessservices/interfaces/ProcessSPOrders"/>
</wsdl:definitions>