<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="com/junglesea/transforms/processOrderResponseMsg_2_submitSupplierOrderResponseMsg.map" md5sum="ba89bb859429b5977fa4bca54bda473a" version="7.0.101" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.101
*
*   Mapping file:		processOrderResponseMsg_2_submitSupplierOrderResponseMsg.map
*   Map declaration(s):	processOrderResponseMsg_2_submitSupplierOrderResponseMsg
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FMoonlightLibrary%252Fcom%252Fjunglesea%252Fapps%252Fmoonlight%252FProcessPurchaseOrder%257DprocessOrderResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FSupplierPartnerDomain-v1_0%252Fcom%252Fjunglesea%252Fbusinessservices%252Finterfaces%252FProcessSPOrders%257DsubmitSupplierOrderResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="http://MoonlightLibrary/com/junglesea/apps/moonlight/ProcessPurchaseOrder"
    xmlns:in2="wsdl.http://MoonlightLibrary/com/junglesea/apps/moonlight/ProcessPurchaseOrder"
    xmlns:out="http://CustomerDomain-v1_0/com/junglesea/bo"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out2="http://SupplierPartnerDomain-v1_0/com/junglesea/bo/msg"
    xmlns:out3="http://ProductDomain-v1_0/com/junglesea/bo"
    xmlns:out4="http://CommonDomain-v1_0/com/junglesea/bo"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:out5="wsdl.http://SupplierPartnerDomain-v1_0/com/junglesea/businessservices/interfaces/ProcessSPOrders"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out6="http://BillingDomain-v1_0/com/junglesea/bo"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:out7="http://SupplierPartnerDomain-v1_0/com/junglesea/businessservices/interfaces/ProcessSPOrders"
    xmlns:out8="http://CustomerDomain-Msg/com/junglesea/bo"
    xmlns:map="http://AccessServices-Moonlight2/com/junglesea/transforms/processOrderResponseMsg_2_submitSupplierOrderResponseMsg"
    exclude-result-prefixes="in in2 map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:processOrderResponseMsg_2_submitSupplierOrderResponseMsg"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:processOrderResponseMsg_2_submitSupplierOrderResponseMsg">
    <body>
      <out7:submitSupplierOrderResponse>
        <outputParams>
          <SupplierPartnerOrder>
            <!-- a simple data mapping: "in:processOrderResponse/purchaseOrder"(string) to "OrderNotes"(string) -->
            <xsl:if test="in:processOrderResponse/purchaseOrder">
              <OrderNotes>
                <xsl:value-of select="in:processOrderResponse/purchaseOrder"/>
              </OrderNotes>
            </xsl:if>
          </SupplierPartnerOrder>
        </outputParams>
      </out7:submitSupplierOrderResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
