<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="eligibilityCheckProcess" targetNamespace="http://EligibilityCheck/com/junglesea/solution/eligibility/process/eligibilityCheckProcessArtifacts" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://EligibilityCheck/com/junglesea/solution/eligibility/process/eligibilityCheckProcessArtifacts" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl0="http://EligibilityCheckLibrary/com/junglesea/solution/eligibilityCheck/interfaces/EligibilityCheckInterface" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <plnk:partnerLinkType name="EligibilityCheckInterfacePLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:EligibilityCheckInterface"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="approveEligibilityPLT">
    <plnk:role name="Reference">
      <plnk:portType name="wsdl0:EligibilityCheckInterface"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="../../eligibilityCheck/interfaces/EligibilityCheckInterface.wsdl" namespace="http://EligibilityCheckLibrary/com/junglesea/solution/eligibilityCheck/interfaces/EligibilityCheckInterface"/>
</wsdl:definitions>