<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="BetaInventoryService"
	targetNamespace="http://junglesea.com/BetaInventoryService"
	xmlns:bons0="http://Junglesea/Backend1/BetaInventoryService"
	xmlns:bons1="http://junglesea.com/BetaInventory" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://junglesea.com/BetaInventoryService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<xsd:schema targetNamespace="http://Junglesea/Backend1/wsdl/BetaInventoryService">
		</xsd:schema>
		<xsd:schema targetNamespace="http://Junglesea/Backend1/BetaInventoryService">
		</xsd:schema>
		<xsd:schema targetNamespace="http://junglesea.com/BetaInventoryService">
			<xsd:import namespace="http://junglesea.com/BetaInventory"
				schemaLocation="CheckItemAvailability.xsd" />
			<xsd:import namespace="http://junglesea.com/BetaInventory"
				schemaLocation="ShowItemAvailability.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="CheckItemAvailability">
		<wsdl:part element="bons1:CheckItemAvailability" name="CheckItemAvailability" />
	</wsdl:message>
	<wsdl:message name="ShowItemAvailability">
		<wsdl:part element="bons1:ShowItemAvailability" name="ShowItemAvailability" />
	</wsdl:message>
	<wsdl:portType name="BetaInventoryService">
		<wsdl:operation name="CheckItemAvailability">
			<wsdl:input message="tns:CheckItemAvailability" name="CheckItemAvailability" />
			<wsdl:output message="tns:ShowItemAvailability" name="ShowItemAvailability" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding
		name="BetaInventoryServiceExport_BetaInventoryServiceHttpBinding"
		type="tns:BetaInventoryService">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="CheckItemAvailability">
			<soap:operation soapAction="" />
			<wsdl:input name="CheckItemAvailability">
				<soap:body parts="CheckItemAvailability" use="literal" />
			</wsdl:input>
			<wsdl:output name="ShowItemAvailability">
				<soap:body parts="ShowItemAvailability" use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service
		name="BetaInventoryServiceExport_BetaInventoryServiceHttpService">
		<wsdl:port
			binding="tns:BetaInventoryServiceExport_BetaInventoryServiceHttpBinding"
			name="BetaInventoryServiceExport_BetaInventoryServiceHttpPort">
			<soap:address
				location="http://localhost:9081/jungleseacom/BetaInventoryService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>